### ISSUE TITLE
Change to allow the brain to easily run on an EC2 instance

### ISSUE THREAD

**Issue by tbenade** [dylanmei/hubot-s3-brain#1]
Hi Dylan,

Would you be interested in a pull request that would allow the brain to be more easily run on an EC2 instance with valid IAM role configured. Currently the validation you have prohibits the brain from running on a correctly configured (with IAM instance role) EC2 instance or EB or ECS container instance.

Essentially this [code](https://github.com/dylanmei/hubot-s3-brain/blob/master/scripts/brain.coffee#L52)

```
config = {
  accessKeyId: process.env.HUBOT_S3_BRAIN_ACCESS_KEY_ID || process.env.HUBOT_AWS_ACCESS_KEY_ID,
  secretAccessKey: process.env.HUBOT_S3_BRAIN_SECRET_ACCESS_KEY || process.env.HUBOT_AWS_SECRET_ACCESS_KEY
}

```

and this [code](https://github.com/dylanmei/hubot-s3-brain/blob/master/scripts/brain.coffee#L72)

```
if !key && !secret && !bucket
    throw new Error('S3 brain requires HUBOT_S3_BRAIN_ACCESS_KEY_ID, ' +
      'HUBOT_S3_BRAIN_SECRET_ACCESS_KEY and HUBOT_S3_BRAIN_BUCKET configured')
```

Excerpt from the documentation reads.

> Credentials from IAM Roles for EC2 Instances
> 
> If you are running your application on Amazon EC2, you can leverage EC2's IAM roles functionality in order to have credentials automatically provided to the instance.
> 
> If you have configured your instance to use IAM roles, the SDK will automatically select these credentials for use in your application, and you do not need to manually provide credentials in any other format.

**Comment by dylanmei** [comment]
Yes that would be great!

**Comment by Grummfy** [comment]
check this : https://github.com/ocadotechnology/hubot-s3-brain

**Comment by stephanlindauer** [comment]
@Grummfy why not send a pull request?
